# Generated by Django 4.2.4 on 2024-09-25 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Gynecologue', 'Gynecologue'), ('Administrateur', 'Administrateur'), ('Secretaire', 'Secretaire'), ('Infirmier', 'Infirmier'), ('TTechnicienLaboratoire', 'TechnicienLaboratoire'), ('Pharmacien', 'Pharmacien'), ('TechnicienEchographe', 'TechnicienEchographe')], max_length=22),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
