# Generated by Django 4.2.4 on 2024-09-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='doctor',
            new_name='medecin',
        ),
        migrations.AddField(
            model_name='gynecologue',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='gynecologue',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('patient', 'Patient'), ('gyn', 'Gynécologue'), ('secr', 'Secrétaire'), ('pharm', 'Pharmacien'), ('inf', 'Infirmier')], max_length=22),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicienechographe',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicienechographe',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
    ]
