# Generated by Django 4.2.4 on 2024-10-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_dossiermedical_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echographie',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.patient'),
        ),
        migrations.AddField(
            model_name='echographie',
            name='technicien_echographe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.technicienechographe'),
        ),
        migrations.AddField(
            model_name='echographie',
            name='type_echographie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
