# Generated by Django 4.2.4 on 2024-11-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_echographie_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyse', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('gynecologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.gynecologue')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.patient')),
                ('pharmacien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.pharmacien')),
                ('technicienEchographe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.technicienechographe')),
                ('technicienLaboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.technicienlaboratoire')),
            ],
        ),
    ]
