# Generated by Django 4.2.4 on 2024-11-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_analyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='gynecologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.gynecologue'),
        ),
    ]
