# Generated by Django 4.2.4 on 2024-11-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_dossiermedical_gynecologue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='annee_naissance',
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_medicals',
            field=models.TextField(blank=True),
        ),
    ]
