# Generated by Django 4.2.4 on 2024-11-04 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0010_rename_date_of_birth_patient_annee_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='analyse',
            field=models.ManyToManyField(to='application.analyse'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='type',
            field=models.CharField(default='Type non spécifié', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='gynecologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.gynecologue'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
