# Generated by Django 4.2.4 on 2024-11-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_dossiermedical_gynecologue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='gynecologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.gynecologue'),
        ),
    ]
